# Site
repository: antonella-schiavoni/antonella-schiavoni.github.io 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Antonella Schiavoni
title: Senior Machine Learning Engineer
email: antonellaschiavon2@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  antonella-schiavoni
linkedin_username: antonellaschiavoni


# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  HelloðŸ‘‹ my name is Antonella Schiavoni, Iâ€™m a Senior Machine Learning Engineer with over 5 years of experience. I am currently working at ASAPP as Machine Learning Engineer in the NLP Modeling team and also working on my Data Sciente Master thesis.
  I enjoy learning new things and building prototypes to apply the knowledge ðŸ¤“. I work with Python ðŸ and a wide range of ML frameworks and libraries. I am always looking for opportunities to learn and apply something new.
  The technologies that I currently have the most experience working with are: Python, Pytorch, Docker, Kubernetes, Circle CI, Jenkins, R, Sklearn, Pandas, Git, ML Flow and AWS services.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Email Classification Service 
        link: https://github.com/antonella-schiavoni/email-classification-service
        link_text: Github Code
        quote: >
          Classify your email text using this email classification service
        description: | # this will include new lines to allow paragraphs
          A web application that contains a django service and a machine learning model that given a request with the text of an email, can detect if the email is spam or not.
      - layout: left
        title: Evolutionary Tic Tac Toe 
        link: https://github.com/antonella-schiavoni/evolutionary-tic-tac-toe
        link_text: Github Code
        quote: >
          Apply evolutionary algorithm to play tic tac toe
        description: | # this will include new lines to allow paragraphs
          This project consists of several scripts that are used to run the evolutionary algorithm to train an Agent to play tic tac toe.
      - layout: left
        title: Entity Recognition Service
        link: https://github.com/antonella-schiavoni/entity-recognition-service
        link_text: Github Code
        quote: >
          Detect the different entities that are in a text.
        description: | # this will include new lines to allow paragraphs
          A rest api that exposes and endpoint that returns the entities found in a text.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Asapp
        sub_title: Senior Machine Learning Engineer
        caption: January 2019 - present
        link: https://www.asapp.com/
        description: | # this will include new lines to allow paragraphs
          â€¢ Deploy and monitor new ML model services into production.
          â€¢ Build and maintain airflow pipelines for training machine learning models.
          â€¢ Improve deployment pipelines. This involved the migration of our deployment scripts to a full easy-to-use pipeline using lanzar and spinnaker.
          â€¢ Ownership over one of the most important services that summarizes conversations.
          â€¢ Train and maintain Asappâ€™s customer machine learning models which also involved the computation of model metrics to evaluate model performance, and the creation of custom monitors in Datadog.
          â€¢ Perform data analysis on modelâ€™s results to evaluate ab test performance.
          â€¢ Launch new clients to Asappâ€™s ML platform.
          â€¢ Technical and Cultural Fit Interviewer
          â€¢ Adapt service and model to run using GPU workers in production
          â€¢ Decouple service to be used separated from ASAPP product. This involves the design and implementation of a public API
          â€¢ Promoted to Senior Machine Learning in November 2021
      - layout: right
        title: Experian
        sub_title: Data Engineer Analyst
        caption: January 2018 - January 2019
        link: https://www.experian.com/
        description: | # this will include new lines to allow paragraphs
          â€¢ Analyse and confirm the integrity of source data to be evaluated.
          â€¢ Generate reports following quality control procedures to document analysis and model findings.
          â€¢ Collaborate in the elaboration of complex data structures and programs.
          â€¢ Create documentation, specifications, diagrams, and charts to provide direction to business and other IT teams.
          â€¢ Perform data analysis and data modeling to create source to target mappings.
          â€¢ Feature engineering. Use of Machine learning algorithms to create new variables.
          â€¢ Analyse structured and unstructured data.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Universidad de San Andres, Bs As, Argentina
        sub_title: MSc. in Data Science
        caption: 2020 - 2022
        description: | # this will include new lines to allow paragraphs
          During my masters at Universidad de San Andres I worked on improving my analytical skills as well as my modeling and statistical skils. I had the opportunity to study and apply a wide variety of machine learning techniques, as well as learning and understanding the mathematical background beahind this algorithims. In the two year program I've improve my knowlgede on statistics, programming for data analysis, data visualization, supervised and unsupervised networs, NLP, neural networks with an image processing approach, and geostatistics and graph networks.
      - layout: top-right
        title: Universidad del Noroeste de la Provincia de Buenos Aires (UNNOBA), JunÃ­n, Argentina
        sub_title: BSc. in Computer Engineering
        caption: 2011 - 2017)
        description: | # this will include new lines to allow paragraphs
          During my degree at UNNOBA I developed lots of important skills such as programming, debugging, agile, team work, project management. The main focuse was software development and principles of programming which I constantly use in my day to day work.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
