# Site
repository: antonella-schiavoni/antonella-schiavoni.github.io 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Antonella Schiavoni
title: Senior Machine Learning Engineer
email: antonellaschiavon2@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  antonella-schiavoni
linkedin_username: antonellaschiavoni


# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  HelloðŸ‘‹ my name is Antonella Schiavoni, Iâ€™m a Senior Machine Learning Engineer with over 5 years of experience. I am currently working at ASAPP as Machine Learning Engineer in the NLP Modeling team and also working on my Data Sciente Master thesis.
  I enjoy learning new things and building prototypes to apply the knowledge. I work with Python and a wide range of ML frameworks and libraries. I am always looking for opportunities to learn and apply something new.
  The technologies that I currently have the most experience working with are: Python, Pytorch, Docker, Kubernetes, R, Sklearn, Pandas, Git, AWS services.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Email Classification Service 
        link: https://github.com/antonella-schiavoni/email-classification-service
        link_text: Github Code
        quote: >
          Classify your email text using this email classification service
        description: | # this will include new lines to allow paragraphs
          A web application that contains a django service and a machine learning model that given a request with the text of an email, can detect if the email is spam or not.
      - layout: left
        title: Evolutionary Tic Tac Toe 
        link: https://github.com/antonella-schiavoni/evolutionary-tic-tac-toe
        link_text: Github Code
        quote: >
          Apply evolutionary algorithm to play tic tac toe
        description: | # this will include new lines to allow paragraphs
          This project consists of several scripts that are used to run the evolutionary algorithm to train an Agent to play tic tac toe.
      - layout: left
        title: Entity Recognition Service
        link: https://github.com/antonella-schiavoni/entity-recognition-service
        link_text: Github Code
        quote: >
          Detect the different entities that are in a text.
        description: | # this will include new lines to allow paragraphs
          A rest api that exposes and endpoint that returns the entities found in a text.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
